### ISSUE TITLE
Uptobox Links Not Showing Up

### ISSUE THREAD

**Issue by silentangelph** [rishavanand/Alldebrid-PHP-torrent-script#1]
It seems that uptobox.php is not working. You might want to check that out. Thanks!

Or you may guide me cuz idk what's happening why the links aint showing up even the fact that it has been uploaded on my account. I have checked it already buti when I clicked "Display Links" on downloaded. Nothing shows up. It says "Links Not Found" 

Hope you may resolve this or help me. Thanks!

**Comment by pijanify** [comment]
Yeah, same problem with @SilentAngelPH .. But my problem is when clicked "Download" button, it says "Anchor Href Values Not Found!!!" .. Am I missing some part? Please help.

**Comment by rishavanand** [comment]
I have made some changes. You can check it now.
